; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Thu Dec 12 2024 17:52:10 GMT+0800 (Singapore Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


