; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Thu Dec 12 2024 17:52:10 GMT+0800 (Singapore Standard Time)
G91               ; relative positioning
G1 H1 Y-240 F3000 ; move quickly to Y axis endstop and stop there (first pass)
G1 H2 Y5 F6000    ; go back a few mm
G1 H1 Y-240 F240  ; move slowly to Y axis endstop once more (second pass)
G90               ; absolute positioning

