; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Thu Dec 12 2024 17:52:12 GMT+0800 (Singapore Standard Time)
; Wait for set temperatures to be reached
M116 P0

